### ISSUE TITLE
Testing the package

### ISSUE THREAD

**Issue by lgatto** [lgatto/ProteomicsAnnotationHubData#1]
I have added my `SourceType`s to the `expectedSourceTypes` in my local `AnnotationHubData`. Without the calls to `makeAnnotationHubResource`, things look fine. With the latter, I get

```
Error in assign(mname, def, where) : 
  cannot add bindings to a locked environment
Error : unable to load R code in package ‘ProteomicsAnnotationHubData’
```

@sonali-bioc Is there a way I can bypass this (as I did above in updating the `expectedSourceTypes`), or so you need to go ahead and try in on the server?

**Comment by sonali-bioc** [comment]
I have just checked in "mzML", "mzTab", "mzid" as expectedSourceTypes  in version 0.0.222 of AnnotationHubData

**Comment by sonali-bioc** [comment]
Line 89 in makePXD000001.R has a typo - I think it should be AMDRecord instead of AHMRecord

It still doesnt fix the error. I get (below) while running R CMD INSTALL on ProteomicsAnnotationHubData
Error in assign(mname, def, where) :
  cannot add bindings to a locked environment

**Comment by lgatto** [comment]
Typo fixed, thanks. 

Do you see this error locally or on the server?

**Comment by sonali-bioc** [comment]
yes. I do.

**Comment by sonali-bioc** [comment]
Line 83 in makePXD000001.R should be Recipe = .Recipe[i]
