### ISSUE TITLE
File on AH S3

### ISSUE THREAD

**Issue by lgatto** [lgatto/ProteomicsAnnotationHubData#3]
One of the 4 test files should be on the AH amazon S3 instance. It should be `TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid`, as this is the only one that is not available on the PRIDE ftp site, but the following does not seem to report anything

``` r
> Map(AnnotationHubData:::.ftpFileInfo,
+     url = "http://s3.amazonaws.com/annotationhub//pride/data/archive/2012/03/PXD000001/", 
+     filename = "TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210.mzid",
+     tag = NA_character_)
PXD000001
$`http://s3.amazonaws.com/annotationhub/pride/data/archive/2012/03/PXD000001/`
                                                                       fileurl
1 http://s3.amazonaws.com/annotationhub//pride/data/archive/2012/03/PXD000001/
  date size genome
1 <NA>   NA   <NA>
```

@sonali-bioc - could you check which file, if any, is on AH S3.

**Comment by sonali-bioc** [comment]
Dear @lgatto 

Any file from your recipe that needs to end up on amazon s3 - will be added to amazon s3 - will only end up on amazon s3 - when I run the code finally using the internal machine inside Hutch. So when I run the code .. the file will be created and automatically uploaded to amazon s3 - or you if you have the file precreated, you can transfer it to me using dropbox, one drive and I can upload it to amazon s3.. does that make sense?

also I see a '//' slash in the url - we should correct the code to get rid of it . 

Thanks
Sonali.

**Comment by lgatto** [comment]
Thanks for the clarification. Will amend the code for the double `/`.
